<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        Promise.resolve('1')
        .then(res => {
          console.log(res)
        })
        .finally(() => {
          console.log('finally')
        })
      Promise.resolve('2')
        .finally(() => {
          console.log('finally2')
          return '我是finally2返回的值'
        })
        .then(res => {
          console.log('finally2后面的then函数', res)
        })
//1 finally2 finally finally2后面的then函数 2
/*finally()方法不管Promise对象最后状态如何都会执行，finally()方法定位回调函数不接受任何的参数，在.finally()函数中是无法知道Promise的最终状态是resolved
还是rejected,它最终的返回默认是一个上一次的Promise对象值，不过如果抛出一个异常则会返回异常的Promise对象*/
function runAsync (x) {
  const p = new Promise(r => setTimeout(() => r(x, console.log(x)), 1000))
  return p
}
function runReject (x) {
  const p = new Promise((res, rej) => setTimeout(() => rej(`Error: ${x}`, console.log(x)), 1000 * x))
  return p
}
Promise.all([runAsync(1), runReject(4), runAsync(3), runReject(2)])
       .then(res => console.log(res))
       .catch(err => console.log(err))
// 1s后输出
1
3
// 2s后输出
2
Error: 2
// 4s后输出
4

    </script>
</body>
</html>